name: quote_generator

on:
  workflow_dispatch:
  schedule:
  - cron: "9 19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - name: Generate quote
      run: npm run generate
    - name: Update README.md
      run: |
        git config --global user.email "phamvanthuyen2802@gmail.com"
        git config --global user.name "ThuyenPV"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
